copyright: Copyright © 2008-2026 the <a href="https://ts.sch.gr">Ομάδα Τεχνικής Στήριξης</a>
dev_addr: 0.0.0.0:7101
edit_uri: tree/main/docs
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.superfences
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      title: Περιεχόμενα σελίδας
plugins:
  - minify:
      minify_html: false
  - search
  - with-pdf:
      author: Έκδοση pdf του https://ts.sch.gr/wiki/windows
      copyright: Copyright © 2008-2026 Τεχνική Στήριξη ΣΕΠΕΗΥ
      cover_title: ΣΕΠΕΗΥ με Windows
      cover_subtitle: Οδηγός εγκατάστασης, διαμόρφωσης & χρήσης
      debug_html: false
      enabled_if_env: ENABLE_PDF_EXPORT
      heading_shift: true
      ordered_chapter_level: 3
      output_path: windows.pdf
      toc_level: 3
      toc_title: Πίνακας περιεχομένων
repo_url: https://github.com/pe86/windows
site_name: Τεχνική Στήριξη ΣΕΠΕΗΥ
site_url: https://ts.sch.gr/wiki/windows
strict: false
theme:
# favicon: favicon.ico
  features:
    - todo-navigation.instant
    # https://squidfunk.github.io/mkdocs-material/upgrade/#contentcodecopy
    - content.code.copy
  language: el
  # Enable `locale: el` when it becomes available
  # https://www.mkdocs.org/user-guide/choosing-your-theme/#mkdocs-locale
  # locale: el
  logo: stylesheets/ts-logo.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Αλλαγή σε σκούρο θέμα
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Αλλαγή σε ανοιχτό θέμα
  titles_only: true
nav:
  - index.md
  - Αυτόνομες Εγκαταστάσεις:
      - Windows 11:
        - client/index.md
        - client/requirements.md
        - client/compatibility.md
        - Εγκατάσταση:
          - client/installation/index.md
          - client/installation/manual/index.md
          - client/installation/unattended/index.md
        - client/basic-settings/index.md
